language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-octoblu-channel' ]; then cd .. && eval "mv $currentfolder generator-octoblu-channel" && cd generator-octoblu-channel; fi

